import { parseNotice } from "./agents/notice-parser.js";
import { lookupTenantRights, getSupportedStates } from "./agents/law-lookup.js";
import { detectViolations } from "./agents/violation-detector.js";
import { draftDefenseLetter } from "./agents/letter-drafter.js";
import type { AnalysisResult } from "./types.js";

const DISCLAIMER =
  "This analysis is generated by an AI system and is for informational purposes only. " +
  "It does not constitute legal advice and does not create an attorney-client relationship. " +
  "Please consult a qualified tenant rights attorney before taking legal action. " +
  "Many areas have free legal aid services for tenants facing eviction.";

export async function analyzeEvictionNotice(noticeText: string): Promise<AnalysisResult> {
  console.log("[1/4] Parsing eviction notice...");
  const parsedNotice = await parseNotice(noticeText);
  console.log(`      → Notice type: ${parsedNotice.noticeType}, State: ${parsedNotice.state}`);

  const rights = lookupTenantRights(parsedNotice.state);
  if (!rights) {
    const supported = getSupportedStates().join(", ");
    throw new Error(
      `State "${parsedNotice.state}" not yet supported. Currently supported: ${supported}. ` +
      `Please include your state clearly in the notice text.`
    );
  }
  console.log(`[2/4] Loaded ${rights.state} tenant law`);

  console.log("[3/4] Detecting violations...");
  const violations = await detectViolations(parsedNotice, rights);
  console.log(`      → Found ${violations.length} violation(s)`);

  console.log("[4/4] Drafting defense letter...");
  const { letter, summary, actions } = await draftDefenseLetter(parsedNotice, rights, violations);

  return {
    parsedNotice,
    violations,
    defenseSummary: summary,
    recommendedActions: actions,
    defenseLetter: letter,
    disclaimer: DISCLAIMER,
  };
}
