import { extractPackagingInfo } from "./agents/packaging-extractor.js";
import { analyzeVisualAuthenticity } from "./agents/visual-analyzer.js";
import { generateVerdict, buildVerificationGuidance } from "./agents/verdict-agent.js";
import { lookupDrug } from "./services/fda-api.js";
import { checkWHOAlerts } from "./services/who-checker.js";
import type { AnalysisResult } from "./types.js";

const DISCLAIMER =
  "This analysis is generated by AI and cross-referenced against public health databases. " +
  "It is for informational purposes only and does not replace professional pharmaceutical evaluation. " +
  "Always consult a licensed pharmacist or healthcare provider before using any medicine. " +
  "If you suspect a counterfeit medicine, report it to your national medicines regulatory authority.";

export async function analyzeMedicine(
  imageBuffer: Buffer,
  mimeType: string
): Promise<AnalysisResult> {
  console.log("[1/4] Extracting packaging information from image...");
  const packaging = await extractPackagingInfo(imageBuffer, mimeType);
  console.log(`      → Drug: ${packaging.drugName}, Manufacturer: ${packaging.manufacturer}`);

  // Steps 2 & 3 run in parallel — independent of each other
  console.log("[2/4] Running database lookups in parallel (FDA + WHO + visual analysis)...");
  const [fdaRecord, visualAnalysis] = await Promise.all([
    lookupDrug(packaging.drugName).then((fda) => {
      const whoAlert = checkWHOAlerts(
        packaging.drugName,
        packaging.manufacturer,
        packaging.batchNumber ?? undefined
      );
      return { fda, whoAlert };
    }),
    analyzeVisualAuthenticity(imageBuffer, mimeType, packaging.drugName),
  ]);

  const { fda, whoAlert } = fdaRecord;
  console.log(`      → FDA: ${fda.found ? "found" : "not found"}, Recalls: ${fda.recalls.length}, WHO alert: ${whoAlert ? "MATCHED" : "none"}`);
  console.log(`      → Visual quality: ${visualAnalysis.overallQuality}, Print score: ${visualAnalysis.printQualityScore}/100`);

  console.log("[3/4] Generating authenticity verdict...");
  const verdict = await generateVerdict(packaging, fda, whoAlert, visualAnalysis);
  console.log(`      → Verdict: ${verdict.verdict} (score: ${verdict.score}/100)`);

  console.log("[4/4] Building verification guidance...");
  const verificationGuidance = buildVerificationGuidance(packaging, verdict);

  return {
    packaging,
    fdaRecord: fda,
    whoAlertMatch: whoAlert,
    visualAnalysis,
    verdict,
    verificationGuidance,
    disclaimer: DISCLAIMER,
  };
}
